### PR TITLE
fix(luadev): this plugin has been renamed

### PR DESCRIPTION
**Pull request by abzcoding**
[lua-dev.nvim](https://github.com/folke/lua-dev.nvim) is now [neodev.nvim](https://github.com/folke/neodev.nvim)

### CODE REVIEW

**Review by kylo252 — COMMENTED** [review]
there eems to be a minor issue with nvim-notify on first install, no sure what this is about

```log
Error executing vim.schedule lua callback: /home/hatsu/.config/lvim/plugin/packer_compiled.lua:68: Error executing lua: /home/hatsu/.config/lvim/plugin/packer_compiled.lua:485: attempt to
index a nil value
stack traceback:
        /home/hatsu/.config/lvim/plugin/packer_compiled.lua:485: in function </home/hatsu/.config/lvim/plugin/packer_compiled.lua:480>
        [C]: in function '__index'
        ...m/site/pack/packer/start/nvim-notify/lua/notify/init.lua:176: in function 'get_render'
        ...m/site/pack/packer/start/nvim-notify/lua/notify/init.lua:206: in function <...m/site/pack/packer/start/nvim-notify/lua/notify/init.lua:179>
        [C]: in function 'nvim_notify'
        /home/hatsu/.config/lvim/plugin/packer_compiled.lua:68: in function </home/hatsu/.config/lvim/plugin/packer_compiled.lua:67>
stack traceback:
        [C]: in function 'nvim_notify'
        /home/hatsu/.config/lvim/plugin/packer_compiled.lua:68: in function </home/hatsu/.config/lvim/plugin/packer_compiled.lua:67>
```

**Comment by kylo252** [comment]
@abzcoding, can you test if you have the same issue?

```sh
git switch rolling
lvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
git switch fix/lua-dev-3
lvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
```

we should probably update [nvim-notify](https://github.com/rcarriga/nvim-notify/commits/master)

**Comment by abzcoding** [comment]
@kylo252 that is weird, I have no issues 🤔 (and ci doesn't seem to fail) 
but I just did update `nvim-notify` as well, so can you check again?

**Comment by kylo252** [comment]
I have no idea what's going on :disappointed:

it's probably a packer issue that's unrelated, but I also don't know why this exists: https://github.com/folke/neodev.nvim/blob/b2fd8b7f599d116b6dea0aa4e4c179b64e3f65db/after/plugin/lua-dev.lua#L1

**Comment by abzcoding** [comment]
> I have no idea what's going on 😞
> 
> it's probably a packer issue that's unrelated, but I also don't know why this exists: https://github.com/folke/neodev.nvim/blob/b2fd8b7f599d116b6dea0aa4e4c179b64e3f65db/after/plugin/lua-dev.lua#L1

that might be a temporary fix for users till they migrate?

**Comment by lvimuser** [comment]
> that might be a temporary fix for users till they migrate?

seems like it

**Review by lvimuser — APPROVED** [review]
didn't check the notify part, but neodev LGTM, and it was enough to just change the requires in my config.

**Comment by kylo252** [comment]
I'm pretty sure it's a packer issue not playing well with `dap-ui`, you will see [this message](https://github.com/rcarriga/nvim-dap-ui/blob/1cd4764221c91686dcf4d6b62d7a7b2d112e0b13/lua/dapui/init.lua#L127) on  `:PackerCompile` every time :no_mouth:

**Comment by abzcoding** [comment]
> I'm pretty sure it's a packer issue not playing well with `dap-ui`, you will see [this message](https://github.com/rcarriga/nvim-dap-ui/blob/1cd4764221c91686dcf4d6b62d7a7b2d112e0b13/lua/dapui/init.lua#L127) on `:PackerCompile` every time 😶

well I don't see that message at all, this seems a bit strange 🤔 
@lvimuser do you have any issues?

**Pull request merged**
