### PR TITLE
feat: portal integration to jumping between  buffers history

### PR DESCRIPTION
**Pull request by edenac**
# Description

portal plugin added to go to back or forward in buffers history with alt + i and alt + o  beeing like easy-motion of buffers history:
https://github.com/cbochs/portal.nvim

## How Has This Been Tested?
i just added portal plugin and i set the keymaps (alt + i , alt + o) to jumping between buffers history

- Run command `:lua require("portal").jump_backward()`
- Run command `:lua require("portal").jump_forward()`
- I just assigned that both functions in keymapps alt + i  and alt + o

### CODE REVIEW

**Comment by edenac** [comment]
sc

**Comment by cpea2506** [comment]
Do you think it should be managed to be put into core plugins?

**Comment by LostNeophyte** [comment]
It looks like it's very easy to add it from config.lua. I don't think this should be in core, maybe add it to the website in extra plugins

**Comment by edenac** [comment]
ok, thanks  for the feedback guys

**Pull request closed without merging**
