### PR TITLE
Please... reverse history and cycle next telescope bindings

### PR DESCRIPTION
**Pull request by afridley**
# Description

Reverses the bindings for cycle history and cycle next in telescope so that ctrl j and k go back to navigating through telescope lists while ctrl n and p will cycle the history of searches.

Fixes #(issue)
#1274 
## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. \
Provide instructions so we can reproduce. \
Please also list any relevant details for your test configuration.

- Open a project
- select find files
- use ctrl j and k to move up and down the list.
- use ctrl n and p to cycle history

### CODE REVIEW

**Comment by ChristianChiarulli** [comment]
I liked this behavior too, could we just cycle history with tab and s-tab?

**Comment by abzcoding** [comment]
as mentioned in #1137 and also [the Default telescope.nvim mapping](https://github.com/nvim-telescope/telescope.nvim/blob/79644ab67731c7ba956c354bf0545282f34e10cc/lua/telescope/mappings.lua#L12)

i think it should stay the way it is

**Comment by abzcoding** [comment]
the-office-dont-you-dare

**Comment by afridley** [comment]
@abzcoding This is great as far as a config solution.

I still wonder if the default shouldn't be the other way around though to match the existing navigation for qflist and lsp menus. Since in both those you can use some form of j and k.

though n and p are used in lsp menus as well but not on quickfix lists. Maybe quickfix navigation should also get n and p alongside j and k for consistency across the app.

**Comment by afridley** [comment]
@abzcoding @ChristianChiarulli I think we need something like
```
lvim.builtin.which_key.mappings["t"]
```
except for telescope
```
lvim.builtin.telescope.mappings["i"]
lvim.builtin.telescope.mappings["n"]
```

I created a feature request for this here
https://github.com/LunarVim/LunarVim/issues/1279

**Comment by afridley** [comment]
This works big thanks to @abzcoding 

```lua
lvim.builtin.telescope.on_config_done = function()
  local actions = require "telescope.actions"
  lvim.builtin.telescope.defaults.mappings.i["<C-j>"] = actions.move_selection_next
  lvim.builtin.telescope.defaults.mappings.i["<C-j>"] = actions.move_selection_next
  lvim.builtin.telescope.defaults.mappings.i["<C-k>"] = actions.move_selection_previous
  lvim.builtin.telescope.defaults.mappings.i["<C-n>"] = actions.cycle_history_next
  lvim.builtin.telescope.defaults.mappings.i["<C-p>"] = actions.cycle_history_prev
end
```

**Comment by afridley** [comment]
@ChristianChiarulli @abzcoding This should be good to go. I couldn't do anything about the quickfix list as it just like navigating normally and I wasn't about to rebind n, p ctrl-n or ctrl-p to be up and down when editing text.

So I rebound n and p to move selection in telescopes normal mode as well as insert. Then added a comment in both configs that will overwrite both telescopes insert and normal mode to use j and k

**Pull request merged**
