### PR TITLE
fix(telescope): ignore .git/*

### PR DESCRIPTION
**Pull request by meijieru**
Better default for telescope find_files.

### CODE REVIEW

**Review by cpea2506 — APPROVED** [review]

**Review by kylo252 — CHANGES_REQUESTED** [review]
This option is not passed directly to `fd` or `ripgrep`, see https://github.com/nvim-telescope/telescope.nvim/blob/0b1c41ad8052badca6e72eafa4bc5481152e483e/doc/telescope.txt#L618
```help
     If you only want `file_ignore_patterns` for `find_files` and
    `grep_string`/`live_grep` it is suggested that you setup `gitignore`
    and have fd and or ripgrep installed because both tools will not show
    `gitignore`d files on default.
```

instead, maybe it's recommended to add `~/.config/fd/ignore`

```gitconfig
.git/*
*.git/*
.node-modules/*
```

**Comment by meijieru** [comment]
Adding them to `~/.config/fd/ignore` doesn't work in `find_files`.

**Comment by opalmay** [comment]
`.git/` is automatically gitignored so it doesn't show in either `fd` or `rg`. This is the default behavior

**Comment by LostNeophyte** [comment]
> `.git/` is automatically gitignored so it doesn't show in either `fd` or `rg`. This is the default behavior

files in .git do show up using `Telescope find_files`, but not with `Telescope git_files`

**Comment by meijieru** [comment]
This can be done by manually set
```lua
  lvim.builtin.telescope.pickers.find_files = {
    find_command = { "rg", "--files", "--hidden", "--glob", "!**/.git/*" },
  }
```

**Pull request closed without merging**
