### PR TITLE
docs: make installation instructions more explicit

### PR DESCRIPTION
**Pull request by leungyauming**

### CODE REVIEW

**Review by mihil99 — COMMENTED** [review]
Looks good, makes docs slightly more understandable

**Comment by hardboiledphil** [comment]
I was just installing for first time and did find that a bit confusing - change makes sense as it mentions 0.8 required previously

**Review by Z3rio — APPROVED** [review]
Looks good to me!

**Review by gnmearacaun — CHANGES_REQUESTED** [review]
This is now out of date since the release of v1.2.0. Master is the new rolling and depends on nvim 0.9 whereas the release recommends nvim v0.8.0. Installation instructions have been updated and moved from readme.md to docsite.

**Comment by gnmearacaun** [comment]
Rolling branch is depreciated

**Pull request closed without merging**
