### PR TITLE
fix(installer): more robust yarn validation

### LINKED ISSUE #2112: [Bug]: Unable to install without administrative privilages. Please set you NPM_HOME correctly and try again.
### Problem description

steps to reproduce
1. use the one-click script to install
2. use nvm to install node dependencies

the following problem arises

Detecting platform for managing any additional neovim dependencies
--------------------------------------------------------------------------------
Would you like to install LunarVim's NodeJS dependencies?
[y]es or [n]o (default: no) : y
[ERROR] Unable to install without administrative privilages. Please set you NPM_HOME correctly and try again.

### LunarVim version

latest stable release

### Neovim version (>= 0.5)

0.6.01

### Relevant log output

```shell
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Screenshots

Screenshot (12)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

### PR DESCRIPTION
**Pull request by fbaltor**
# Description

Today if you have a problem installing the nodejs dependencies for a given package ("npm" or "yarn"), the installer simply quits before trying the other ones. This PR guarantees that all nodejs package managers have failed before quitting.

Fixes #2112 

## How Has This Been Tested?
1. no need to execute the entire script, you can change the last line

```bash
# main "$@"
install_nodejs_deps   # just call the function we want
```

2. now set npm/yarn prefix to some nonsense.
```console
$ yarn config set prefix "/blah/blah"
$ yarn global bin
/blah/blah/bin
$ bash install.sh
[ERROR] Unable to install using [yarn] without administrative privileges.
Installing node modules with npm..
All NodeJS dependencies are successfully installed
```

### CODE REVIEW

**Comment by kylo252** [comment]
I'm not really sure what this solves, since yarn can basically read npm's configuration. What we can do instead is just issue a warning instead of aborting the installation, but I'm not sure if treesitter would fail gracefully in this case.

**Comment by fbaltor** [comment]
Well, without this the installer quits before trying all options. Is this the expected behavior?

**Comment by fbaltor** [comment]
> Well, without this the installer quits before trying all options. Is this the expected behavior?

Well, without this the installer quits before trying all options. Is this the expected behavior?

**Comment by kylo252** [comment]
As I just mentioned, yarn will basically use npm's prefix, so it shouldn't really make a difference, and it's not worth it to add this additional handling imo. We should leave this extra complexity for a proper package-manger.

I think that a user could just install the node deps manually or fix their npm's config.

**Comment by fbaltor** [comment]
IDK. I got very confused when the installation failed even though my npm's was correct. And it is not clear to me that yarn reads npm's configurations by default. IMO the installer should work if there is an available option.

**Comment by kylo252** [comment]
> IDK. I got very confused when the installation failed even though my npm was correct. And it is not clear to me that yarn reads npm's configurations by default.

Maybe it's just an `fnm` thing. Could you change the PR to check for `yarn global bin` instead if `yarn` was chosen?

https://classic.yarnpkg.com/en/docs/cli/global

**Comment by fbaltor** [comment]
> Maybe it's just an `fnm` thing. Could you change the PR to check for `yarn global bin` instead if `yarn` was chosen?
> 
> https://classic.yarnpkg.com/en/docs/cli/global

Sure thing! But leaving my modifications?

**Comment by kylo252** [comment]
> Sure thing! But leaving my modifications?

Let's simplify the logic then

```diff
diff --git a/utils/installer/install.sh b/utils/installer/install.sh
index cfedd77..5c25cc0 100755
--- a/utils/installer/install.sh
+++ b/utils/installer/install.sh
@@ -222,19 +222,28 @@ function __install_nodejs_deps_yarn() {
 function __validate_node_installation() {
   local pkg_manager="$1"
   local manager_home
-  manager_home="$($pkg_manager config get prefix 2>/dev/null)"
+
+  if ! command -v "$pkg_manager" &>/dev/null; then
+    return 1
+  fi
+
+  if [ "$pkg_manager" == "npm" ]; then
+    manager_home="$(npm config get prefix 2>/dev/null)"
+  else
+    manager_home="$(yarn global bin 2>/dev/null)"
+  fi
 
   if [ ! -d "$manager_home" ] || [ ! -w "$manager_home" ]; then
-    echo "[ERROR] Unable to install without administrative privileges. Please set your NPM_HOME correctly and try again."
-    exit 1
+    echo "[ERROR] Unable to install using [$pkg_manager] without administrative privileges."
+    return 1
   fi
+  return 0
 }
 
 function install_nodejs_deps() {
   local -a pkg_managers=("yarn" "npm")
   for pkg_manager in "${pkg_managers[@]}"; do
-    if command -v "$pkg_manager" &>/dev/null; then
-      __validate_node_installation "$pkg_manager"
+    if __validate_node_installation "$pkg_manager"; then
       eval "__install_nodejs_deps_$pkg_manager"
       return
     fi
```

**Comment by fbaltor** [comment]
I'll check for some tests in previous PR's that updated the installer tomorrow (26/12). Thank you for the help, @kylo252!

**Comment by kylo252** [comment]
LGTM! Thank you ❤️

**Pull request merged**
