### PR TITLE
refactor(ci): better path handling

### PR DESCRIPTION
**Pull request by kylo252**
# Description

- Make Packer installation path more robust
- Remove the need to use hombrew for sha256sum

## How Has This Been Tested?

Should pass the CI tests

### CODE REVIEW

**Comment by argapost** [comment]
After this commit lvim cannot find my .config/lvim and it falls back to .config/nvim where there is no config.lua etc. so I get an error.
From the code I see that you get the config_dir from:

```lua
function _G.get_config_dir()
 local lvim_config_dir = os.getenv "LUNARVIM_CONFIG_DIR"
```
 but there is no such env var in my system, should I define it myself?

**Comment by rebuilt** [comment]
It's possible you have an older version of the launcher installed.  What is the content of `cat ~/.local/bin/lvim` ?

**Comment by argapost** [comment]
Yeap just realised it, I git pull so I don't run the launcher therefore the bin/lvim stays the same.

**Comment by kylo252** [comment]
@argapost, so it still an issue?

**Comment by argapost** [comment]
Yes this has been fixed but now it cannot find the require("lsp").global_setuo function even though i can see it in the file. I am working on it

**Comment by argapost** [comment]
Ok I had to :LuaCacheClear first, all good now thanks.

**Pull request merged**
