### PR TITLE
Make lsp kind icons configurable

### PR DESCRIPTION
**Pull request by xeluxee**
# Description
1. Deprecate `lvim.lsp.completion.item_kind` (it was useless since `cmp` was introduced)
2. Remove `lua/lsp/kind.lua`
3. Add `lvim.lsp.kind_icons`

## How Has This Been Tested?
Put this in your `config.lua`
``` lua
lvim.lsp.kind_icons = {
  Class = "myClass",
  Color = "myColor",
  Constant = "myConstant",
  Constructor = "myConstructor",
  Enum = "myEnum",
  EnumMember = "myEnumMember",
  Event = "myEvent",
  Field = "myField",
  File = "myFile",
  Folder = "myFolder",
  Function = "myFunction",
  Interface = "myInterface",
  Keyword = "myKeyword",
  Method = "myMethod",
  Module = "myModule",
  Operator = "myOperator",
  Property = "myProperty",
  Reference = "myReference",
  Snippet = "mySnippet",
  Struct = "myStruct",
  Text = "myText",
  TypeParameter = "myTypeParameter",
  Unit = "myUnit",
  Value = "myValue",
  Variable = "myVariable",
}
```

### CODE REVIEW

**Comment by xeluxee** [comment]
Any news about this?

**Comment by kylo252** [comment]
@xeluxee, would it possible for you to rebase this work on #1584? Just so I don't have to go through a lot of conflicts.

**Comment by xeluxee** [comment]
Sure, I'll send this PR to `lang-refactor` branch
@kylo252  I've just got a problem: after `:LspInstall sumneko_lua` what should I do to make lsp start with #1584?

**Comment by kylo252** [comment]
> Sure, I'll send this PR to `lang-refactor` branch  

I changed the base branch of the PR, you just need to rebase your local branch and fix the conflicts. You may not need to modify all that much in the new branch, but I would be really grateful if you can unify all the entries to LSP kind. 

> I've just got a problem: after `:LspInstall sumneko_lua` what should I do to make lsp start?

You need to run `make update`. I'm gonna push the LvimUpdate PR which will make things easier.

**Comment by xeluxee** [comment]
Just moved `kind_icons` dictionary to cmp settings, since this setting is managed only by `nvim-cmp`

Put this in your `config.lua`
``` lua
lvim.builtin.cmp.formatting.kind_icons = {
  Class = "myClass",
  Color = "myColor",
  Constant = "myConstant",
  Constructor = "myConstructor",
  Enum = "myEnum",
  EnumMember = "myEnumMember",
  Event = "myEvent",
  Field = "myField",
  File = "myFile",
  Folder = "myFolder",
  Function = "myFunction",
  Interface = "myInterface",
  Keyword = "myKeyword",
  Method = "myMethod",
  Module = "myModule",
  Operator = "myOperator",
  Property = "myProperty",
  Reference = "myReference",
  Snippet = "mySnippet",
  Struct = "myStruct",
  Text = "myText",
  TypeParameter = "myTypeParameter",
  Unit = "myUnit",
  Value = "myValue",
  Variable = "myVariable",
}
```

**Comment by xeluxee** [comment]
This PR is a mess.
Closing in favour of #1657

**Pull request closed without merging**
