### PR TITLE
feat(neovim): neovim 0.8 compatibility

### PR DESCRIPTION
**Pull request by abzcoding**
# Description

Make sure we are compatible with neovim 0.8

https://www.reddit.com/r/neovim/comments/u5si2w/breaking_changes_inbound_next_few_weeks_for/

### CODE REVIEW

**Comment by abzcoding** [comment]
don't merge it yet, test it a bit :)

**Comment by kylo252** [comment]
I think I managed to re-write the trickiest parts of this, which are the conditional `format_on_save` and `lsp_document_highlight`, but I'd still need some minor modifications to adapt them to lvim 🧑‍🏭 

https://github.com/kylo252/dotfiles/commit/af1497e13c1e1f2dd67a1a86411192953090e81e

**Comment by abzcoding** [comment]
> I think I managed to re-write the trickiest parts of this, which are the conditional `format_on_save` and `lsp_document_highlight`, but I'd still need some minor modifications to adapt them to lvim 🧑‍🏭
> 
> [kylo252/dotfiles@af1497e](https://github.com/kylo252/dotfiles/commit/af1497e13c1e1f2dd67a1a86411192953090e81e)

that is wonderful 👍

**Comment by gelfand** [comment]
Hi, possible to merge this?

**Comment by kylo252** [comment]
I pulled latest rolling into master as well, just to help those using nightly on master (they really shouldn't.... 😄)

**Pull request merged**
