### PR TITLE
fix(lsp): avoid duplicates server

### PR DESCRIPTION
**Pull request by meijieru**
# Description

Avoid launch duplicated lsp server.
Related https://github.com/LunarVim/LunarVim/issues/2012

### CODE REVIEW

**Review by kylo252 — CHANGES_REQUESTED** [review]
As mentioned, I'm still not able to reproduce #2042, so I don't know what is it exactly that we're trying to solve.

Can you please expand on the intended logic here? I feel like there might be a cleaner way to do it.

**Comment by abzcoding** [comment]
> As mentioned, I'm still not able to reproduce #2042, so I don't know what is it exactly that we're trying to solve.
> 
> Can you please expand on the intended logic here? I feel like there might be a cleaner way to do it.

@kylo252 basically this
Screen Shot 2021-12-07 at 4 23 45 PM

**Comment by meijieru** [comment]
In short, `lvim_lsp_utils.is_client_active` is not reliable here as the server takes time to start.
So I set `_client_infos.status` to `loading` to avoid that.

**Comment by kylo252** [comment]
Thanks for the explanation. I'm pretty sure that there's no need to introduce another variable to track this. I'll test a few different approaches and report back.

**Comment by kylo252** [comment]
Thanks for pointing me in the right direction! 

Superseded by #2048

**Pull request closed without merging**
