### PR TITLE
Fix: Install Nodejs

### PR DESCRIPTION
**Pull request by ZepbachVNTM**
[Bugfix]: Fix install NodeJs

### CODE REVIEW

**Comment by kylo252** [comment]
Hey, any reason why your `npm install` is not running on a user directory?

**Review by ChristianChiarulli — APPROVED** [review]

**Comment by Uzaaft** [comment]
Most likely, (just a hypothesis), author has not set up npm to use a folder in /home/$USER, which in turn requires sudo to install global packages. I had the same issue while setting up arch the first time.

**Comment by Uzaaft** [comment]
A couple of reasons why not to use sudo can be found here(behind paywall, I think): https://medium.com/@ExplosionPills/dont-use-sudo-with-npm-still-66e609f5f92

**Review by abzcoding — CHANGES_REQUESTED** [review]
we should not use sudo, we can warn users to install those separately or fix their nodejs

**Comment by Uzaaft** [comment]
@abzcoding You can close the PR. It does not fix anything.

**Comment by kylo252** [comment]
> Most likely, (just a hypothesis), author has not set up npm to use a folder in /home/$USER, which in turn requires sudo to install global packages. I had the same issue while setting up arch the first time.

What I wanted to know is if there there's a reason why he can't change it, since I figured it's the default way on his system probably. I should have framed my question better 😄.

And I 100% agree with the rest of the your comment, thank you for the useful links, much appreciated!

**Comment by kylo252** [comment]
Closed due to lack of a response from the author. Please let me know if you still need help with it later on.

**Pull request closed without merging**
