### PR TITLE
feat: automatic null ls setup with mason null ls and selection algorithm

### LINKED ISSUE #4246: Automatic Null-ls setup with mason-null-ls and selection algorithm
### Feature Description

LunarVim inspired me a lot in my own configuration, in fact I adapted most of your LSP setup. I extended the LSP setup with an algorithm that selects null-ls sources by a certain criteria - I will link a PR to this enhancement request. The basic idea is to automate the setup of null-ls entirely and allowing the user/developer to parse it's own configuration.

The algorithm calculates a score for each source of a null-ls method and the winning sources will be installed by mason and registered by null-ls. I'm going to explain the algorithm in my PR thouroughly.

### Describe the alternatives you have considered

_No response_

### Support information

_No response_

### PR DESCRIPTION
**Pull request by quantumfate**
# Description

TODO:

- [x] on first time setup one and only one method won't be registered

This PR involves a selection algorithm as well as the integration of the mason plugin for null-ls. It will automatically select null-ls sources for it's available methods which are defined by null-ls [here](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/_meta/filetype_map.lua). 

Thanks in advance for reading and review. I'm open to making changes as well as discussing the future of this PR to eventually integrate it in LunarVim.

### The entry point

The entry point for the setup of `sources` is identical to the method you use for launching lsp server. A line to the template generation has been added that will call the `lvim.lsp.null-ls.manager.setup()` function when opening a specific filetype.

### The algorithm

As the title of this PR suggests the algorithm will select sources for methods to be registered. It is supposed to further bridge the gap between `null-ls` and `mason` as `mason-null-ls` already does. In fact `mason-null-ls` will be used to properly resolve the mason packages for given sources.

The algorithm will fetch available methods and sources on a specific filetype from [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/_meta/filetype_map.lua). 

1. (Optional) It will then apply user configurations, see [Configuration](#Configuration)
2. It will select sources for methods that were not set yet, see [Selection criteria](#selection-criteria)
3. Install the sources when available through mason
3.1 Reattached null-ls to the buffer using mason events to ensure that installed source is properly added to the buffer 
5. Register the sources in null-ls (Uses LunarVim's builtin way of registering sources)

#### Selection criteria

The algorith will select sources for methods by calculating a score for each source with the following formular:

```lua
local score = base_score * source_amount + priority
```

- `base_score` is the base score of any source but sources that are available through mason automatically rank higher than sources that are not
- `source_amount` if a particular source is available for more than one method it will be selected for all methods that it is available for. Meaning that this source will rank a higher score than sources that are only available once. The reason for this is that on automatic setups like this you would want the experience of the user to be as pleasant as possible. Therfor we select as little sources as possible to avoid conflicts between the methods. Additionally this will reduce the amount of packages installed as well.
- `priority` some sources get the same score when they are available to each method by the same amount. In this case sources that appear first in the input will be prioritized

By creating a set of scores for all methods wich are also mapped to their source we use the `selection sort algorithm` to sort these sources for each method from highest to lowest. All thats left to do is to select the first element of the sorted list and do the rest of the magic for installation and registration.

See [How Has This Been Tested?](#how-has-this-been-tested?) for some ekamples.

## Configuration

The following configuration options exist:

### Packages

Some null-ls sources are not maintained by mason and if they require further setup it is possible to create a file named `your-source-name.lua` in the `lvim.lsp.null-ls.packages` directory that returns a mason package spec (see mason api) that will be installed and later registered in null-ls.

### Providers

Similar to the providers in `lvim.lsp.providers` there is a folder as such in `lvim.lsp.null-ls` called `providers` as well. A file called `your-sources-ft.lua` such as `lua.lua` and `py.lua` allows the user to manually select a source for a specific method that will not be overriden by the algorithm as in fact the algorith mwill only select sources for methods that the user didn't manually select.

The file could look like this [again: see whats possible in null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/_meta/filetype_map.lua):

the available javascrip methods are:

```lua
  javascript = {
    code_actions = { "eslint", "eslint_d", "refactoring", "xo" },
    diagnostics = { "deno_lint", "eslint", "eslint_d", "jshint", "semistandardjs", "standardjs", "xo" },
    formatting = { "deno_fmt", "dprint", "eslint", "eslint_d", "prettier", "prettier_d_slim", "prettier_eslint", "prettier_standard", "prettierd", "rome", "rustywind", "semistandardjs", "standardjs" }
  },
```

and we could create a file called `javascript.lua` with our specific configuration to tell the algorithm to select, install and register these sources for their respective methods:

```lua
  return {
    code_actions = { "eslint" },
    diagnostics = { "deno_lint" },
    formatting = { "deno_fmt" }
  }
```

### Sources

The directory `lvim.lsp.null-ls.sources` allows the user to inject specific source settings by creating a file `your-source-name.lua` with any custom logic necessary for the specific source. This configuration will then be invoked like you are used to with the `setup` function from `code_actions.lua`, `formatters.lua` and `linters.lua`. 

MPORTANT: The sources setup mentioned in the [LunarVim documentation here](https://www.lunarvim.org/docs/configuration/language-features/linting-and-formatting) is likely stale because any configurations made here will likely be overriden by the algorithm, when it selects the same or a different source for that particular method. 

fixes #4246 

### Filetype: lua

The input:

```lua
  lua = {
    code_actions = { "refactoring" },
    diagnostics = { "luacheck", "selene" },
    formatting = { "lua_format", "stylua" }
  },
```
Result:

As you can see we have no common sources between the methods so the first best will be selected.

image

### Filetype: python

The input:

```lua
  python = {
    code_actions = { "refactoring" },
    diagnostics = { "flake8", "mypy", "pycodestyle", "pydocstyle", "pylama", "pylint", "pyproject_flake8", "ruff", "semgrep", "vulture" },
    formatting = { "autoflake", "autopep8", "black", "blue", "isort", "pyflyby", "pyink", "reorder_python_imports", "ruff", "usort", "yapf" }
  },
```
Result:

As you can see the source `ruff` is common across `diagnostics` and `formattin` hence its selected.

image

### CODE REVIEW

**Comment by quantumfate** [comment]
Any idea why the pipeline fails?

**Comment by LostNeophyte** [comment]
> Any idea why the pipeline fails?

you have duplicates in core_plugins, and in the snapshot json you added mason-nvim-dap instead of mason-nvim-dap.nvim

**Comment by quantumfate** [comment]
> > Any idea why the pipeline fails?
> 
> you have duplicates in core_plugins, and in the snapshot json you added mason-nvim-dap instead of mason-nvim-dap.nvim

Ok thanks one step further. I'm going to address the failing tests on the weekend

**Comment by LostNeophyte** [comment]
just to be clear, I have no idea if this pr will be merged, If I were you I'd wait before working on it

**Comment by quantumfate** [comment]
Yeah, might be wise. I was expecting so as the base branch was changed from a feature branch to master, tho.

**Comment by LostNeophyte** [comment]
all the PRs should target the master branch

**Comment by quantumfate** [comment]
Ok good to know - I was confused because contribution guideline state to target a feature branch

**Comment by quantumfate** [comment]
Also let me know if you want any changes to the feature and I will implement them. We can discuss the future of this PR.

**Comment by quantumfate** [comment]
I will close my PR and the linked issue in favor of https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621

**Pull request closed without merging**
