### PR TITLE
fix: lvim bin `-u` issue

### PR DESCRIPTION
**Pull request by LostNeophyte**
fixes https://github.com/LunarVim/LunarVim/issues/3612, https://github.com/MordechaiHadad/bob/issues/132

### CODE REVIEW

**Comment by LostNeophyte** [comment]
> This has worked for me, but I guess the solution could be more specific:
> 
> It looks like the problem is that $NVIM_APPNAME is empty when installing `nvim` with snap. Then, the following target precisely and only that (by fallback $NVIM_APPNAME to "nvim" as a default value)
> 
> ```diff
> # ~/.local/bin/lvim
> ...
> +++ [[ ! -z NVIM_APPNAME ]] && export NVIM_APPNAME="nvim"
> export NVIM_APPNAME="${NVIM_APPNAME:-"lvim"}"
> ```

the problem has nothing to do with NVIM_APPNAME, it existed before we added NVIM_APPNAME support

**Review by kylo252 — CHANGES_REQUESTED** [review]
how did you test this btw? I'm worried about it's actually expanding `nvim` that's causing the issue in this case.

**Comment by LostNeophyte** [comment]
> how did you test this btw? I'm worried about it's actually expanding `nvim` that's causing the issue in this case.

you're right, my fix broke -a, I think we should just drop it

**Comment by kylo252** [comment]
> > how did you test this btw? I'm worried about it's actually expanding `nvim` that's causing the issue in this case.
> 
> you're right, my fix broke -a, I think we should just drop it

@LostNeophyte, just to clarify I meant that this would not really handle `nvim` being a shim itself all that well, which I suspect is the case with snaps judging by https://github.com/neovim/neovim-snap/blob/2fdf079b70a8dd594addbf436ab2b9ad3990ba2d/snap/local/nvim-wrapper

argparsing can be a pain, especially in bash when it's multiple layers (of indirection)

maybe we could add a note about using it with snap installations (refer them to use https://github.com/LunarVim/LunarVim-mono/releases instead)

**Pull request closed without merging**
