### PR TITLE
chore: bump core-plugins version

### PR DESCRIPTION
**Pull request by kylo252**
# Description

- chore: parsable core-plugins list
- chore: update nvim-tree's settings
- chore: add plugins' sha generator

### CODE REVIEW

**Comment by kylo252** [comment]
@chase, I think it's better to split the PR, so we'll keep this to update the structure, and then we'll figure out a way to automate this. I also had to revert cmp's SHA since it was failing.

**Comment by chase** [comment]
https://github.com/LunarVim/LunarVim/blob/24be0ef1ef36b8cc725655e920104e9676b72f25/lua/lvim/core/nvimtree.lua#L32

This is apparently deprecated now, but the filters option doesn't seem to work? Might want to pin nvimtree to a version before the bump.

**Comment by kylo252** [comment]
> https://github.com/LunarVim/LunarVim/blob/24be0ef1ef36b8cc725655e920104e9676b72f25/lua/lvim/core/nvimtree.lua#L32
> 
> This is apparently deprecated now, but the filters option doesn't seem to work? Might want to pin nvimtree to a version before the bump.

I updated the setting specifically because the other one was deprecated 😄 
Make sure you've updated the binding in your `config.lua`, as it needs to be moved under `setup`: https://github.com/chase/lvim/blob/2e6c813d4dcf31cf5c1f0b4b3a1178c67aeb911b/config.lua#L190

**Comment by Manndung75** [comment]
Báo

**Pull request merged**
