### PR TITLE
Replacing `luacheck` with `selene`

### PR DESCRIPTION
**Pull request by abzcoding**
# Description

Since the last commit of `luacheck` is 3 years ago,
we should begin to migrate to `selene`

### CODE REVIEW

**Comment by abzcoding** [comment]
current issues that need to be addressed
image

**Comment by kylo252** [comment]
FYI, The new repo now lives under [luarocks/luacheck](https://github.com/luarocks/luacheck)

see the the discussion here: https://github.com/mpeterv/luacheck/issues/198#issuecomment-665867491

---

Lastly, are you sure that about the feature parity?

**Comment by abzcoding** [comment]
if that one was last updated a year ago
image

**Comment by kylo252** [comment]
> even that repo was last updated a year ago

If it ain't broke, don't fix it (?)

Selene appears to have more [open tickets](https://github.com/Kampfkarren/selene/issues) than both luacheck's repos combined, for better or for worse 🤔

**Comment by abzcoding** [comment]
> > even that repo was last updated a year ago
> 
> If it ain't broke, don't fix it (?)
> 
> Selene appears to have more [open tickets](https://github.com/Kampfkarren/selene/issues) than both luacheck's repos combined, for better or for worse thinking

even we have more issues :sweat_smile: 
also it found [these](https://github.com/abzcoding/lvim/commit/d7acc2e220297b5a6501df9b99d69f8581e5eabf), but `luacheck` didn't find them

**Comment by abzcoding** [comment]
sth weird happened with GitHub, gonna reopen this

**Pull request closed without merging**
