### PR TITLE
[Feature] hot reload configurations

### PR DESCRIPTION
**Pull request by Tastyep**
# Description

This work is based on [796](https://github.com/ChristianChiarulli/LunarVim/pull/796) and will stay as a draft until it gets merged.
This pr provides an object for observing file updates, I tested observing multiple files at the same time and it works.
At present, I only observe lv-config, when the config is updated I reload plugins and configurations.

#### Updates
[0] There are still some problems with this, mainly caused by code that is interpreted when the module is loaded, a better approach would be to wrap everything into functions. 

[1] I've reviewed the current problems, and I think [893](https://github.com/ChristianChiarulli/LunarVim/pull/893) would fix them.

## How Has This Been Tested?

- Open lv-config
- Add a plugin to user_plugins
- Observe that it's loaded
- Remove it
- Type y (asked by PackerClean, not sure is this can be automatized)
- Observe that the plugin has been removed

### CODE REVIEW

**Comment by kylo252** [comment]
Not sure how related it is to this, but I noticed that a broken config will sometimes brick Packer until you actually delete `plugin/packer_compiled.lua` first and then you can actually use Packer again.

I think it might be worth implementing a mechanism to detect such cases and remove it first, if it's feasible. Or maybe just always perform a "clean" compile. Although I'm not sure how safe it is 😄

**Comment by Tastyep** [comment]
> Not sure how related it is to this, but I noticed that a broken config will sometimes brick Packer until you actually delete `plugin/packer_compiled.lua` first and then you can actually use Packer again.
> 
> I think it might be worth implementing a mechanism to detect such cases and remove it first, if it's feasible. Or maybe just always perform a "clean" compile. Although I'm not sure how safe it is smile

We could simply make a function called on one whichkey mapping, the entry for packer already exists.

**Comment by rebuilt** [comment]
Great work on 796.  This one looks like it will also move the project in a good direction.

**Comment by abzcoding** [comment]
@Tastyep  can we have this plz :pleading_face:

**Comment by Tastyep** [comment]
Fine, I'll work on it today ^^

**Comment by chase** [comment]
@Tastyep is this still necessary with how things are currently setup? Any features not implemented yet?

**Comment by Tastyep** [comment]
> @Tastyep is this still necessary with how things are currently setup? Any features not implemented yet?

No, I'll close it

**Pull request closed without merging**
