### PR TITLE
fix: handle deprecated telescope.builtin.internal

### PR DESCRIPTION
**Pull request by dlanileonardo**
# Description

When require `telescope.builtin.internal`, produce an error Module no found.

Telescope => [init.lua](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/init.lua)

## How Has This Been Tested?

- Open Preview Colorschemes

### CODE REVIEW

**Comment by kylo252** [comment]
Thanks!

**Comment by owod24** [comment]
Hello, I am facing this issue as well. How do I go about fixing it?

**Comment by owod24** [comment]
> Hello, I am facing this issue as well. How do I go about fixing it?

I saw the changes that were made. I reinstalled lunarvim and it was solved

**Comment by cizordj** [comment]
Thank you so much for this

**Pull request merged**
