### PR TITLE
feat: rounded border for hover and signatureHelp

### PR DESCRIPTION
**Pull request by ChristianChiarulli**

### CODE REVIEW

**Comment by LostNeophyte** [comment]
this needs to be configurable so it won't conflict if the user decides to add noice.nvim

**Comment by LostNeophyte** [comment]
or we can use this, then there's no need to add new config options
```diff
diff --git a/lua/lvim/lsp/init.lua b/lua/lvim/lsp/init.lua
index 6dea3f77..1cb0d1fe 100644
--- a/lua/lvim/lsp/init.lua
+++ b/lua/lvim/lsp/init.lua
@@ -111,6 +111,15 @@ function M.setup()
   require("lvim.lsp.null-ls").setup()
 
   autocmds.configure_format_on_save()
+
+  local function set_handler_opts_if_not_set(name, handler, opts)
+    if debug.getinfo(vim.lsp.handlers[name], "S").source:match(vim.env.VIMRUNTIME) then
+      vim.lsp.handlers[name] = vim.lsp.with(handler, opts)
+    end
+  end
+
+  set_handler_opts_if_not_set("textDocument/hover", vim.lsp.handlers.hover, { border = "rounded" })
+  set_handler_opts_if_not_set("textDocument/signatureHelp", vim.lsp.handlers.signature_help, { border = "rounded" })
 end
 
 return M
```

**Comment by ChristianChiarulli** [comment]
I'm not aware of the conflict with noice, if this snippet is compatible with noice and whatever issue it presents then we can go with this. @LostNeophyte

**Comment by LostNeophyte** [comment]
> 

it fixes the issue

**Pull request merged**
