### PR TITLE
refactor(keymaps)!: don't hijack H/L by default

### PR DESCRIPTION
**Pull request by benediktms**
# Description

Buffer cycling keymaps should be delegated to which-key. These keymaps fulfil the same role and are therefore redunant.

part of https://github.com/LunarVim/LunarVim/issues/2872#issuecomment-1201616659

## How Has This Been Tested?

- Buffer cycling is implemented and tested here https://github.com/LunarVim/LunarVim/pull/2873/commits/5f9f711c93c79ef63410390f8b47a0fc3cf0ea5f

### CODE REVIEW

**Review by rebuilt — APPROVED** [review]

**Comment by rebuilt** [comment]
Uppercase `H` and `L` are very basic movement keys.   Overriding these seems like a mistake.  

Even though this pr deletes the `H` and `L` bindings, LunarVim still provides whichkey bindings to cycle through buffers so users will still have that built-in.  

That said, I recognize that these keybindings have been in LunarVim for a while and some people may prefer to keep these bindings in.  

Anyone that still wants the `H` and `L` keybindings can still add them to their config

```
	lvim.keys.normal_mode["<S-l>"] = ":BufferLineCycleNext<CR>"
	lvim.keys.normal_mode["<S-h>"] = ":BufferLineCyclePrev<CR>"
```

Or they can specify other bindings, eg

```
	vim.api.nvim_set_keymap("n", "<A-l>", ":BufferLineCycleNext<CR>", { noremap = true, silent = true })
	vim.api.nvim_set_keymap("n", "<A-h>", ":BufferLineCyclePrev<CR>", { noremap = true, silent = true })

	lvim.keys.normal_mode["<A-Right>"] = ":BufferLineCycleNext<CR>"
	lvim.keys.normal_mode["<A-Left>"] = ":BufferLineCyclePrev<CR>"

```

**Review by kylo252 — COMMENTED** [review]
How about adding them to `config.example.lua` instead? that way it's also easily searchable for anyone than having to refer to this PR.

**Review by kylo252 — APPROVED** [review]
LGTM! 🚀

**Comment by danielo515** [comment]
Removing this keys that have been this long in LunarVim it's a major breaking change.
People (like me) is already used to this, and I would say that they are more convenient than what they do by default, and way way more convenient than having to use which-key for something you do as often as changing to next buffer.
You only have to give a quick read to the lunar vim chat to see that people love this bindings and that they are used to them.
This will frustrate a lot of people the day they update lunar vim to realise that their usual workflow does not work, and when something is so deep into your muscular memory it is hard to understand why. Then people will have to waste some time to find this PR, or open a new issue, or ask for help in the chat.
Overriding vim defaults is a sensitive thing, but once done you can not just remove it because it will became the new default of a lot of people, and removing it will do as much harm as it did when the decision of overriding it was taken.
LunarVim is not plain vim, so removing this just because "is not vim defaults" seems like a elitist choice. Vim has many key-bindings, if we were going to keep them all by default, then LunarVim will not be adding as much value.
Just my two cents

**Pull request merged**
