### PR TITLE
feat: add lir.nvim again

### PR DESCRIPTION
**Pull request by ChristianChiarulli**

### CODE REVIEW

**Review by kylo252 — COMMENTED** [review]
You can see that the installer is broken with `lir`, I'm not really sure why but it's breaking packer :cry: 

As I said in the other PR, I suspect it's the [autocmd messing things up](https://github.com/ChristianChiarulli/lir.nvim/blob/7d8c6c4a8a1251ec8433b708ddf9b1491a07703f/plugin/lir.vim#L14-L23)

**Comment by rebuilt** [comment]
We had lowered the number of max_jobs because users were experiencing problems 

https://github.com/LunarVim/LunarVim/issues/2891
https://github.com/LunarVim/LunarVim/issues/2794
https://github.com/LunarVim/LunarVim/issues/2793

**Comment by JoshMock** [comment]
Using lvim nightly and have been getting this notification on startup:

```
packer.nvim: Error running config for lir.nvim: ...packer/start/nvim-web-devicons/lua/nvim-web-devicons.lua:1700: bad argument #1 to 'pairs' (table expected, got nil)
```

Maybe related to this change?

**Comment by ChristianChiarulli** [comment]
@JoshMock try running `:PackerSync` and `:PackerCompile`

**Comment by ChristianChiarulli** [comment]
also jj is gone, if people want the feature it's not hard to add

**Comment by Uzaaft** [comment]
I believe that this PR broke Packer for me on Mac. max_jobs = 100 makes Packer freeze, while for.eks max_jobs= 50 does not.

**Comment by JoshMock** [comment]
> @JoshMock try running `:PackerSync` and `:PackerCompile`

`:PackerCompile` doesn't work, just popped up another notification with the [same error](https://github.com/LunarVim/LunarVim/pull/3038#issuecomment-1254256675).

**Comment by ChristianChiarulli** [comment]
we should change the max jobs depending on platform @kylo252

**Comment by JoshMock** [comment]
I figured out that my issue was due to setting `lvim.builtin.nvimtree.active = false`. I wasn't using it so I'd disabled it. Reenabling it fixed [my error](https://github.com/LunarVim/LunarVim/pull/3038#issuecomment-1254256675). Should probably make sure core configs aren't dependent on plugins that can be disabled.

**Comment by ChristianChiarulli** [comment]
good point, right now they're pretty intertwined, I'll try to handle it on a stream

**Pull request merged**
