### PR TITLE
fix: update vim.api.diagnostics to use the new vim.diagnostics

### PR DESCRIPTION
**Pull request by abzcoding**
# Description

customize according to https://github.com/neovim/neovim/pull/15585/files

## How Has This Been Tested?

if `vim.diagnostics` is callable then we need to act different regarding the diagnostics

### CODE REVIEW

**Comment by abzcoding** [comment]
the fuck?
Screen Shot 2021-09-17 at 5 40 46 PM

**Comment by kylo252** [comment]
I think It changed slightly yet again, so you might need to re-test ☠️

**Comment by abzcoding** [comment]
@kylo252 it seems to be working just fine 🤔 
Screen Shot 2021-09-17 at 11 53 12 PM
Screen Shot 2021-09-17 at 11 53 57 PM

**Review by kylo252 — APPROVED** [review]
Thank you for fixing this! We are gonna need to re-visit this again at some point.

**Pull request merged**
