### PR TITLE
[Refactor] Remap whichkey Explorer NvimTreeToggle

### PR DESCRIPTION
**Pull request by jorgeOmurillo**
# Description

Please include a summary of the change and which issue is fixed. \
List any dependencies that are required for this change.

Fixes #(issue)
- Remap whichkey Explorer to lua command

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. \
Provide instructions so we can reproduce. \
Please also list any relevant details for your test configuration.

- Run command `:mycommand`
- Check logs
- ...

### CODE REVIEW

**Comment by abzcoding** [comment]
there is only a single issue, what happens if someone has disabled nvim-tree
do we still want to show that in which-key?

i'm fine with it though

**Comment by rebuilt** [comment]
I'm fine with it as is.  It shouldn't take setting an nvimtree callback to remove this mapping.

In the past we've done something like this to set conditional mappings.

```lua
if(lvim.builtin.nvimtree.active)
  lvim.builtin.which_key.mappings["e"] = { "<cmd>NvimTreeToggle<CR>", "Explorer" }
end
```

**Comment by jorgeOmurillo** [comment]
@abzcoding @rebuilt I can push that condition if so. What do you guys think?

**Comment by Tastyep** [comment]
Related: https://github.com/LunarVim/LunarVim/pull/1406#discussion_r702261627

I wouldn't merge this as it is, because we have other files where which-key mappings are defined in builtins' config.

To be frank, I don't know how this works in the first place, we edit `lvim.builtin.which_key.mappings` which is used in which-key `setup` (soon `config`) function. How does that work, is which-key supposed to be configured last, how does it work if it is configured first ?

**Comment by nahojer** [comment]
@Tastyep this is related to https://github.com/LunarVim/LunarVim/issues/1422 which I posted a few days ago. Fixing this issue would make me fall in love with LunarVim so much more. This is the only thing that bugs me with LunarVim at the moment.

What about providing a callback function for each builtin plugin that is called after after all plugins have been loaded? Similar to, or instead of, the existing callback function `on_config_done = nil` that is invoked as the last thing in `M.setup`, maybe one could have a callback function `on_config_loaded` that is called after all other plugins have been loaded? For instance, in core/builtins/init.lua, one could have:

```lua
function M.config(config)
  for _, builtin_path in ipairs(builtins) do
    local builtin = require(builtin_path)
    builtin.config(config)
  end
  for _, builtin_path in ipairs(builtins) do
    local plugin_conf = plugin configuration from some path trickery?
    local plugin = require from some path trickery?
    lvim[plugin_conf].on_config_loaded(plugin)
  end
end
```

**Comment by Tastyep** [comment]
> What about providing a callback function for each builtin plugin that is called after after all plugins have been loaded? Similar to, or instead of, the existing callback function `on_config_done = nil` that is invoked as the last thing in `M.setup`.

I think it is also something that we need on our side, we need to make sure dependencies are loaded before executing some logic, so I'm not against implementing this kind of mechanism.
Just give it some time as I'm already making big changes on #1406

**Comment by nahojer** [comment]
Absolutely, thanks!

**Comment by rebuilt** [comment]
I don't think the leader key table really belongs to whichkey.  It's used by other plugins and the end user.  

Maybe it belongs in `lvim.keys.leader_keys` ?

**Comment by Tastyep** [comment]
Some updates on this, that's how I think it should be done

https://github.com/LunarVim/LunarVim/pull/1406/commits/257add693e17d9ff738590c5eea8ee953f9a0f3d#diff-1db1be37fe64f29eeec18cb160ed468f80f648bbf4d9f6d80441975f3326b0a1R103-R104

My reasons are that doing it this way, we don't leak information into the `which-key` builtin and we only register the mapping if the builtin is active.

**Comment by abzcoding** [comment]
tyvm for your effort, this has been fixed in another PR, 
so now you can change it to whatever you want in your config.lua
```lua
lvim.builtin.which_key.mappings["e"] = { "<cmd>RnvimrToggle<CR>", "Ranger" }
```

**Pull request closed without merging**
