### PR TITLE
fix: support text if marksman lang server

### PR DESCRIPTION
**Pull request by ChristianChiarulli**

### CODE REVIEW

**Comment by LostNeophyte** [comment]
i think we should allow text for all servers, (or have a deny-list instead of an allow-list) here's a problem with c++ caused by this filter https://github.com/LunarVim/LunarVim/issues/3842

**Comment by ChristianChiarulli** [comment]
my worry is that it's pretty noisy, I'm not sure it's super helpful in most cases. I wasn't aware of the C++ macro issue tho... not sure what they best thing is here. 

I guess a configurable deny list is a good idea.

**Comment by ChristianChiarulli** [comment]
I'm just going to remove the text filter for now, we can work on config for this later: https://github.com/LunarVim/LunarVim/issues/4147

**Comment by ravilock** [comment]
> i think we should allow text for all servers, (or have a deny-list instead of an allow-list) here's a problem with c++ caused by this filter #3842

Just for added context, I also found some problem but with SQL caused by this filter.
https://github.com/joe-re/sql-language-server/issues/219

**Pull request merged**
