### PR TITLE
docs: Update Readme

### PR DESCRIPTION
**Pull request by umop3plsdn**
Something like this to start

# Description

summary of the change

fixes #(issue)

## How Has This Been Tested?

- Run command `:mycommand`
- Check logs
- ...

### CODE REVIEW

**Review by OkelleyDevelopment — APPROVED** [review]
This is how Chris had described on stream, so I think it should be good to go :sunglasses:

**Comment by OkelleyDevelopment** [comment]
It might need a few adjustments once the next release is finalized though (at least that's what was also said on stream)

**Comment by umop3plsdn** [comment]
Ya I was thinking maybe it needs a special thanks for the people who have donated and stuff like that? what do you think chris? Also, anything else you mentioned that I can't remember?

**Review by ChristianChiarulli — APPROVED** [review]

**Comment by vonPB** [comment]
nice stuff

**Pull request merged**
