### PR TITLE
[Hotfix] update tailwindcss cmd path to match lspinstall

### PR DESCRIPTION
**Pull request by abzcoding**
# Description

Fix tailwindcss address bcz of [this commit](https://github.com/kabouzeid/nvim-lspinstall/commit/bd3adbb94f07ee12f7a721ec45a94e7825c32c66#diff-2f2bb4dfdb18304474c7e8e159b5d96ba5dacca10502f99c8c93e92959ed6f9b)

## How Has This Been Tested?

open a sample file that uses tailwindcss and observer that it works!

### CODE REVIEW

**Comment by abzcoding** [comment]
@yassinebridi can you confirm if this fixes your issue or not?

**Comment by abzcoding** [comment]
cc: @hulufei @ChristianChiarulli

**Comment by yassinebridi** [comment]
It is getting the right TailwindCSS path now:
```
.local/share/nvim/lspinstall/tailwindcss/node_modules/.bin/tailwindcss-language-server --stdio
```
Screen Shot 2021-08-30 at 14 51 34

But weirdly enough, it's not working, i'm not getting any classes when `<C-space>`
Screen Shot 2021-08-30 at 14 53 38

**Comment by abzcoding** [comment]
let me check if i can fix it or not

**Comment by abzcoding** [comment]
@yassinebridi can you try doing this
```vim
:LspInstall typescript
```

**Comment by abzcoding** [comment]
nvm i think you need a config file for tailwindcss to work
```lua
    root_dir = root_pattern('tailwind.config.js', 'tailwind.config.ts', 'postcss.config.js', 'postcss.config.ts', 'package.json', 'node_modules', '.git')
```

**Comment by yassinebridi** [comment]
Screen Shot 2021-08-30 at 15 27 17

This is from the same folder, using coc.nvim with this plugin rodrigore/coc-tailwind-intellisense

I might have to reinstall everything and see.

**Comment by abzcoding** [comment]
ok plz create a separate issue for that, i need to dig deeper, lets merge the path fix first 😅

**Pull request merged**
