### PR TITLE
[Bugfix] instead of wrapping the `gl` diagnostics, split them

### PR DESCRIPTION
**Pull request by abzcoding**
# Description

Screen Shot 2021-09-21 at 9 55 00 PM

### CODE REVIEW

**Comment by abzcoding** [comment]
@lallenfrancisl @Jacob87
can you test this out and let me know if the issues are fixed or not?

**Comment by abzcoding** [comment]
you can test it using
```sh
cd ~/.local/share/lunarvim/lvim
git reset --hard
git checkout rolling
git pull
git checkout -b abzcoding-bugfix/split-notwrap rolling
git pull https://github.com/abzcoding/LunarVim.git bugfix/split-notwrap
lvim
```
then run `:LvimCacheReset` for good measure

**Comment by lallenfrancisl** [comment]
@abzcoding Yes its fixed now

**Comment by Jacob87** [comment]
@abzcoding Yes I can confirm this is better now
#### before
image
#### now
image

Even if we don't get a new line for the second type error message (for the TypeScript at least - as shown above), I'm not sure we can do much about it on our side.
But now the result is exactly as it was before, thanks a lot abz! :heart:

**Review by Tastyep — APPROVED** [review]

**Comment by abzcoding** [comment]
well that was a waste of time 😅 
Screen Shot 2021-09-22 at 11 54 11 AM

**Pull request merged**
