### PR TITLE
Setup tailwindcss language server

### PR DESCRIPTION
**Pull request by hulufei**

### CODE REVIEW

**Comment by abzcoding** [comment]
https://github.com/LunarVim/LunarVim/pull/1343

**Comment by ChristianChiarulli** [comment]
is it this easy to do this?

**Comment by hulufei** [comment]
@ChristianChiarulli  Yeah, it works, unless I missed something.

**Comment by ChristianChiarulli** [comment]
cool if you can cleanup the merge conflicts i'll merge this, I'd rather have this than multiple servers tbh, that's just too confusing imo.

**Comment by hulufei** [comment]
@ChristianChiarulli Done.

**Comment by abzcoding** [comment]
can we at least make it optional?

**Comment by hulufei** [comment]
@abzcoding Done.

**Comment by yassinebridi** [comment]
Hey thank you for this pr, I'm new to this beautiful project.
I was wondering how to get it working, I pulled from rolling, and updated and synced packer as suggested in the `Readme`.
and activated the LSP in `.config/lvim/config.lua` like this:
```lua
lvim.lang.tailwindcss = {
  lsp = {
    active = true
  }
}
```

It doesn't seem to work in a `tsx` file

**Comment by abzcoding** [comment]
@yassinebridi 
we need to update the documentation
add the following to your config.lua
```lua
lvim.lang.tailwindcss.lsp.active=true
```
and then run
```vim
:LspInstall tailwindcss
```

**Comment by yassinebridi** [comment]
nvim is properly identifying tailwindcss, another issue is that it doesn't get the path of the lsp
it gives this error when doing `LspInfo`
```
Unable to find executable, please check your path and ensure the server is installed
```
This script doesn't exist in that path
```
.local/share/nvim/lspinstall/tailwindcss/tailwindcss-intellisense.sh --stdio
```

Although I installed tailwind lsp like this:
```
:LspInstall tailwindcss
```

**Comment by abzcoding** [comment]
Screen Shot 2021-08-30 at 5 57 25 PM
can you check these places, it should be there if you've installed using `lspinstall`

**Comment by yassinebridi** [comment]
Screen Shot 2021-08-30 at 14 31 46

It looks like it is installing another version, apparently, it's not the same folder structure

**Comment by abzcoding** [comment]
oh let me check their repo, maybe we need to update the cmd path

**Comment by abzcoding** [comment]
you are right we probably need to change the cmd part
Screen Shot 2021-08-30 at 6 05 44 PM

**Pull request merged**
