### PR TITLE
chore(plugins): bump version

### PR DESCRIPTION
**Pull request by abzcoding**
# Description

Bump plugin version

### CODE REVIEW

**Comment by kylo252** [comment]
should we merge into master and do a release before this?

**Comment by abzcoding** [comment]
> should we merge into master and do a release before this?

agreed 👍

**Comment by kylo252** [comment]
> agreed 👍

What version number should this be? I feel like semver doesn't have to be linear, is this 1.2.0 or 1.1.0 or something else?

**Comment by abzcoding** [comment]
> > agreed 👍
> 
> What version number should this be? I feel like semver doesn't have to be linear, is this 1.2.0 or 1.1.0 or something else?

i think this should be 1.1.0

**Comment by kylo252** [comment]
> i think this should be 1.1.0

I've pushed the changes and updated the changelog, you should do the release this time tho :)

**Pull request merged**
