### PR TITLE
fix(windows): autocmd requires forward slashes

### LINKED ISSUE #1959: [Bug]: autocmd for reloading `config.lua` do not work in windows
#### Steps

1. Open `config.lua`
2. Make some changes and save it 

#### Expected behaviour

LunarVim will be reloaded through the autocmd:
```lua
      { "BufWritePost", user_config_file, "lua require('lvim.config'):reload()" },
```

#### Actural behaviour
Reloading didn't happen

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

0.5.1

### Relevant log output

_No response_

### Screenshots

_No response_

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

### PR DESCRIPTION
**Pull request by kylo252**
Fixes #1959

### CODE REVIEW

**Comment by kylo252** [comment]
@younger-1, can you please test this?

**Comment by younger-1** [comment]
It works on my machine 😄

**Comment by younger-1** [comment]
@kylo252 Sorry I didn't make it clear. It's better not to use `vim.fn.resolve` and set it like this:

```lua
  if vim.loop.os_uname().version:match "Windows" then  
    -- autocmds require forward slashes even on windows
    user_config_file = user_config_file:gsub("\\", "/")
  end
```

Otherwise it will cause error as `string.gsub()` has two return values.
```
E5113: Error while calling lua chunk: Vim:E118: Too many arguments for function: resolve
```

**Comment by kylo252** [comment]
> Otherwise it will cause error as `string.gsub()` has two return values.
> 
> ```
> E5113: Error while calling lua chunk: Vim:E118: Too many arguments for function: resolve
> ```

I'm not getting those errors for this specific usage.

**Pull request merged**
