### PR TITLE
chore: plugin version bump

### PR DESCRIPTION
**Pull request by kylo252**
# Description

Contains a fix for lualine

### CODE REVIEW

**Comment by kylo252** [comment]
@abzcoding last update before 1.0.0? 😃

**Comment by abzcoding** [comment]
> @abzcoding last update before 1.0.0? 😃

😄 yep

**Comment by abzcoding** [comment]
this seems weird 🤔 
Screen Shot 2022-01-04 at 12 26 23 PM

**Comment by kylo252** [comment]
When was the last time you updated the server? the command for it has changed a while ago.

**Comment by abzcoding** [comment]
> When was the last time you updated the server? the command for it has changed a while ago.

i did update the sumneko_lua server today 😢 , so not sure why this happens, let me try some stuff

**Comment by kylo252** [comment]
> i did update the sumneko_lua server today 😢 , so not sure why this happens, let me try some stuff

I re-installed before making that comment. A few things to test: 

1. make sure you're not overriding it
2. make sure that server_available is returning correctly
3. I believe that the lsp-installer has introduced a big change with regard to PATH resolution, so try reverting and see if it fixes this.

**Comment by abzcoding** [comment]
> > i did update the sumneko_lua server today 😢 , so not sure why this happens, let me try some stuff
> 
> I re-installed before making that comment. A few things to test:
> 
> 1. make sure you're not overriding it
> 2. make sure that server_available is returning correctly
> 3. I believe that the lsp-installer has introduced a big change with regard to PATH resolution, so try reverting and see if it fixes this.

it seems like
```lua
requested_server:get_default_options()
```
only has `cmd_env` and not `cmd`
here is how i am overriding `sumneko_lua` -> https://github.com/abzcoding/lvim/blob/main/ftplugin/lua.lua

**Comment by abzcoding** [comment]
Screen Shot 2022-01-04 at 12 41 14 PM

**Comment by abzcoding** [comment]
[which seems to be the case](https://github.com/williamboman/nvim-lsp-installer/blob/e8530f4059279a0d6b5e5f8891d04ffb1ade29a3/lua/nvim-lsp-installer/servers/sumneko_lua/init.lua#L46)

**Comment by abzcoding** [comment]
changing this line fixed it
```lua
  luadev.cmd_env = requested_server:get_default_options().cmd_env
```

**Comment by abzcoding** [comment]
Screen Shot 2022-01-04 at 12 49 29 PM

**Review by abzcoding — APPROVED** [review]

**Pull request merged**
