### PR TITLE
fix(breadcrumbs): add CursorMoved makes winbar seems 10 times faster

### PR DESCRIPTION
**Pull request by nullchilly**
# Description

Related: https://github.com/glepnir/lspsaga.nvim/issues/334

## How Has This Been Tested?

Enabled `lvim.builtin.breadcrumbs.active = true` in `config.lua`

### CODE REVIEW

**Comment by LostNeophyte** [comment]
It was removed for performance reasons https://github.com/LunarVim/LunarVim/pull/3357

**Comment by nullchilly** [comment]
In lspsaga this is fine because the output is cached

**Comment by LostNeophyte** [comment]
We don't use lspsaga

**Comment by nullchilly** [comment]
Alright

**Pull request closed without merging**
