### PR TITLE
feat: add neotest to the core plugins

### PR DESCRIPTION
**Pull request by JBSK8NC**
# Description

Add neotest to LunarVim.

### CODE REVIEW

**Comment by JBSK8NC** [comment]
lvim.plugins = {
 "nvim-neotest/neotest-python",
 }


lvim.builtin.test.active = true
local test = require "lvim.core.neotest"
test.setup {
   adapters = {
     require("neotest-python")({
       dap = { justMyCode = false },
     }),
   },
}

**Comment by JBSK8NC** [comment]
resolves #3215

**Comment by ChristianChiarulli** [comment]
I'll try this on stream soon

**Review by kylo252 — CHANGES_REQUESTED** [review]
## Considerations

#### what are the benefits of adding this to core?

so far, this is only setting up keybinds, which are typically opinionated anyway and are probably better configured by the end-user

#### how does this play with dap?

is there any conflict? is there an integration

#### how to enable extra runners? 

we can **not** add 20 plugins just for test-runner, so this might be better added in `lvim.plugins` where one can add the test-runners they care about

**Comment by kylo252** [comment]
I really doubt we can do this in a reasonable and configurable way.

cc: @abzcoding

**Comment by abzcoding** [comment]
> I really doubt we can do this in a reasonable and configurable way.
> 
> cc: @abzcoding

I'm using this on my own lvim, but I'm not sure what are the benefits of adding this to the core,
we added debugging stuff because it was really hard to configure them properly, but neotest you can easily integrate,
so I'm with kylo on this one

**Comment by JBSK8NC** [comment]
@kylo252 Neotest integrates with nvim-dap, check here. https://github.com/nvim-neotest/neotest#strategies. If no debug adapter is provided. Notify will trigger telling the user dap is not configured.

@kylo252 , @abzcoding 
I agree with the assessment. I think neotest in core does not really provide any less setup of the plugin as the user will have to do most of the setup for the specific test adapters in their config.lua. @ChristianChiarulli I was originally thinking it might be better to add this to the starter.lvim. We could ask the individual language contributors add a testing section for the specific languages. I can also make a config there with the keymaps as an example of setting up testing.

**Pull request closed without merging**
