### PR TITLE
refactor: update impatient

### LINKED ISSUE #1256: [Feature]: Use a dedicated cache directory
### Feature motivation

Right now we're using the same directory as neovim

https://github.com/LunarVim/LunarVim/blob/2345d8cf21fd93a6cf5f716d0345ebce285660a1/lua/default-config.lua#L3

This is problematic for a lot of reasons, I'll try to list some of them:
- overlap in ~/.cache/nvim/lsp.log
- overlap in sessions
- having to delete neovim's cache folder when doing a clean install

### Describe the expected solution

LunarVim should use `~/.cache/lvim` instead. Also make sure that we setup the correct cache path for any/all implicit dependency, e.g. `lsp.log`, and `:mksession`

### LINKED ISSUE #2490: module 'gitsigns.diff_int' not found
### Problem description

I cleaned up lvim with the uninstall script, installed it again and added my configuration.
However, I still get this error, (see also the attached screenshot).
Interestingly, it does not happens every time.

```
Error executing luv callback:
...ite/pack/packer/opt/gitsigns.nvim/lua/gitsigns/async.lua:75: The coroutine failed with this message: ...site/pack/packer/opt/gitsigns.nvim/lua/gitsigns/diff.lua:8: module 'gitsigns.diff_int' not found:
```

### LunarVim version

2567d86  fix(cmp): update nvim-cmp to the latest version (#2467) (#2469)

### Neovim version (>= 0.6.1)

NVIM v0.7.0 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating system/version

Gentoo ~

### Relevant log output

```shell
go: require("go.health").check()
========================================================================
## Binaries
  - INFO: go installed.
  - INFO: Tool installed: gofumpt
  - INFO: Tool installed: golines
  - INFO: Tool installed: richgo
  - INFO: Tool installed: golangci-lint
  - INFO: Tool installed: ginkgo
  - INFO: Tool installed: gopls
  - INFO: Tool installed: gorename
  - INFO: Tool installed: fillstruct
  - INFO: Tool installed: gomodifytags
  - INFO: Tool installed: fixplurals
  - INFO: Tool installed: fillswitch
  - INFO: Tool installed: gotests
  - INFO: Tool installed: dlv
  - INFO: Tool installed: iferr
  - INFO: Tool installed: impl
  - INFO: Tool installed: goimports
  - OK: All binaries installed

## Go Plugin Check
  - OK: lspconfig: plugin is installed
  - OK: nvim-treesitter: plugin is installed
  - OK: guihua: plugin is installed
  - WARNING: nvim-dap-virtual-text: not installed/loaded
  - OK: telescope: plugin is installed
  - WARNING: nvim-treesitter-go is not installed, Please run TSInstall go to install
  - WARNING: nvim-dap-ui: not installed/loaded
  - WARNING: nvim-dap: not installed/loaded
  - WARNING: Not all plugin installed

null-ls: require("null-ls.health").check()
========================================================================
  - OK: stylua: the command "stylua" is executable.
  - OK: goimports: the command "goimports" is executable.
  - OK: luacheck: the command "luacheck" is executable.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - WARNING: **julia**: not available
  - OK: **sh**: `Ok`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.12`
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **python3**: `Python 3.9.12`
  - OK: **node**: `v16.14.1`
  - OK: **Ruby**: `ruby 2.6.9p207 (2021-11-24 revision 67954) [x86_64-linux]`
  - OK: **Go**: `go version go1.18.1 linux/amd64`
  - OK: **curl**: `curl 7.82.0 (x86_64-pc-linux-gnu) libcurl/7.82.0 (GnuTLS/3.7.3) OpenSSL/1.1.1n zlib/1.2.12 libidn2/2.3.2 nghttp2/1.47.0 OpenLDAP/2.6.1`
  - OK: **java**: `Ok`
  - OK: **RubyGem**: `3.3.8`
  - OK: **javac**: `Ok`
  - OK: **npm**: `8.5.0`
  - OK: **pip3**: `pip 22.0.4 from /usr/lib/python3.9/site-packages/pip (python 3.9)`

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.14.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Gentoo 11.2.1_p20220115 p4) 11.2.1 20220115
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - css            ✓ . ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - javascript     ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.9.12
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.9p207 (2021-11-24 revision 67954) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.
      - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

## Node.js provider (optional)
  - INFO: Node.js: v16.14.1
  - INFO: Nvim node.js host: /home/cova/.config/yarn/global//node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.1

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/cova/.cache/nvim/lsp.log
  - INFO: Log size: 1 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gc"**
  - INFO: rhs: `<Cmd>lua require("Comment.api").call("toggle_linewise_op")<CR>g@`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gb"**
  - INFO: rhs: `<Cmd>lua require("Comment.api").call("toggle_blockwise_op")<CR>g@`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"yS"**
  - INFO: rhs: `<Plug>YSurround`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"ys"**
  - INFO: rhs: `<Plug>Ysurround`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>Lc"**
  - INFO: old rhs: `<CMD>edit /home/cova/.config/lvim/config.lua <CR>`
  - INFO: new rhs: `<cmd>edit /home/cova/.config/lvim/config.lua<cr>`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>sr"**
  - INFO: old rhs: `<CMD>Telescope oldfiles<CR>`
  - INFO: new rhs: `<cmd>Telescope oldfiles<cr>`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>st"**
  - INFO: old rhs: `<CMD>Telescope live_grep<CR>`
  - INFO: new rhs: `<cmd>Telescope live_grep<cr>`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>f"**
  - INFO: old rhs: `<CMD>Telescope find_files<CR>`
  - INFO: new rhs: `<cmd>lua require("which-key").execute(1)<cr>`
```

### Screenshots

image

### PR DESCRIPTION
**Pull request by kylo252**
# Description

- update impatient: merge the the latest upstream version.  _it still needs to be loaded before any plugins, so it will have to be managed manually either way_
- feat: use an independent cache directory: overridden `vim.fn.stdpath` to use LUNARVIM_x_DIR instead, since a lot of plugins call this function interally

resolves #1256
fixes #2490

## How to test

- added new tests for `vim.fn.stdpath`: 
https://github.com/LunarVim/LunarVim/blob/211fa202640932844a886553e6d5f5733002442d/tests/specs/bootstrap_spec.lua#L13-L22
- check https://github.com/LunarVim/LunarVim/pull/2477#issuecomment-1102702593

## Notes

For future references: 
- it's easy to restore the original behavior of `vim.fn.stdpath`, by either removing some entries from https://github.com/kylo252/LunarVim/blob/978820b8edc56a12fd0c34664d6adabbe4e51734/lua/lvim/bootstrap.lua#L73-L83, or overriding the function, yet again, in `config.lua`

### CODE REVIEW

**Comment by abzcoding** [comment]
tested with a fuck ton of plugins

1. without this PR                             -> 240 to 260 ms 
2. with this PR(uncommented)       -> 270 to 300 ms
3. with this PR(setup commented) -> 320 to 600 ms

**Comment by kylo252** [comment]
> 1. without this PR                             -> 240 to 260 ms 
> 2. with this PR(uncommented)       -> 270 to 300 ms

Are the cache files growing in size with this PR? I noticed that it might be more gradual with this new upstream implemention.

**Comment by abzcoding** [comment]
> Are the cache files growing in size with this PR? I noticed that it might be more gradual with this new upstream implemention.

I'll try it a bit more and report back

**Comment by abzcoding** [comment]
> wtpr -> without this PR
> pruc -> with this pr setup uncemmented
> prc   -> with this pr and setup commented

| State        | Cache Size     | Startup Time |
|--------------|----------------|--------------|
| wtpr: first  | 388008         | 1696         |
| wtpr: second | 2545147        | 266          |
| wtpr: nth    | 3107775        | 235          |
| pruc: first  | 28080+381451   | 408          |
| pruc: second | 231239+6153682 | 287          |
| pruc: nth    | 231005+6154390 | 274          |
| prc: first   | 0              | 575          |
| prc: second | 0              | 365          |
| prc: nth | 0              | 363          |


i'm on mac and this is my nvim version
```
NVIM v0.8.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by kylo252** [comment]
thanks for all the effort doing all those tests! so far the results seem to indicate a 10% loss in "reported" startup time, but we still get a better profiler, some other neat tricks with overloading `loadfile`, and hopefully get rid of all the remaining errors generated by gitsigns.

btw, have you made some script to automate this? otherwise I can try to adapt this one https://github.com/echasnovski/mini.nvim/tree/main/benchmarks/starter

**Comment by abzcoding** [comment]
>hopefully get rid of all the remaining errors generated by gitsigns.

🤞 


> btw, have you made some script to automate this? otherwise I can try to adapt this one https://github.com/echasnovski/mini.nvim/tree/main/benchmarks/starter

no it was a manual process 😅

**Comment by kylo252** [comment]
@abzcoding, here are more tests using your own config on an M1 machine

image

the `lv3` (e.g. `~/.local/bin/lv3`) command is basically another instance of `lvim` with this branch [impatient-v3](https://github.com/kylo252/LunarVim/tree/impatient-v3), which incorporates a new workaround for handling the cache dir, see https://github.com/kylo252/LunarVim/commit/8ccca6780bf290c292093cafd9a0ed4ec9e0f479, which seems to give the best results out of all three implementations!

<details>
<summary>lv2</summary>

```sh
#!/usr/bin/env bash

export LUNARVIM_RUNTIME_DIR="/tmp/lv3/lunarvim"
export LUNARVIM_CONFIG_DIR="/tmp/lv3/config"
export LUNARVIM_CACHE_DIR="/tmp/lv3/cache"
export LUNARVIM_BASE_DIR="$LUNARVIM_RUNTIME_DIR/lvim"

function install() {
  local
  url="https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh"
  export LV_REMOTE="kylo252/lunarvim.git"
  export LV_BRANCH="impatient-v3"
  bash <(curl -s "$url")

  # NOTE: remember to use the same config
  rm -rf $LUNARVIM_CONFIG_DIR
  gh repo clone abzcoding/lvim $LUNARVIM_CONFIG_DIR

  mkdir -p $LUNARVIM_CACHE_DIR
}

# install

function lvim() {
  nvim -u "$LUNARVIM_BASE_DIR/init.lua" "$@"
}

lvim "$@"
```

</details>

**Comment by abzcoding** [comment]
fantastic, let's merge the third implementation then 👍

**Comment by kylo252** [comment]
> fantastic, let's merge the third implementation then 👍

should I move the `vim.fn.stdpath` change into a separate PR? wdyt?

**Comment by abzcoding** [comment]
> > fantastic, let's merge the third implementation then 👍
> 
> should I move the `vim.fn.stdpath` change into a separate PR? wdyt?

let's keep it in the same PR, it is gonna be one big PR, but at least all changes related to impatient would be in the same place

**Comment by abzcoding** [comment]
not sure why, but it seems like it doesn't recognize the installed lang servers
Screen Shot 2022-04-20 at 2 33 08 PM

**Comment by kylo252** [comment]
> not sure why, but it seems like it doesn't recognize the installed lang servers

It's because it's now using an independent `vim.fn.stdpath`, you need to install them again or move them manually. We could also the lsp-install directory to match the one used before `~/.local/share/nvim/lsp_servers`

**Comment by abzcoding** [comment]
> I think the CI errors are related to how tmp files are handled on macos, could you try the branch and run the tests locally?

this env var is not available on mac machines
`    local xdg_config = os.getenv "XDG_CONFIG_HOME"`

**Comment by abzcoding** [comment]
> > not sure why, but it seems like it doesn't recognize the installed lang servers
> 
> It's because it's now using an independent `vim.fn.stdpath`, you need to install them again or move them manually. We could also the lsp-install directory to match the one used before `~/.local/share/nvim/lsp_servers`

we should probably do that, since the language server binaries are exactly the same for nvim and lvim

**Pull request merged**
